name: sprint2
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=2.19.3 <3.0.0"

dependencies:
  file_picker: ^5.2.7
  flutter:
    sdk: flutter
  flutter_document_picker: ^5.1.0
  flutter_dotenv: ^5.0.2
  flutter_pdfview: ^1.3.0
  flutter_secure_storage: ^8.0.0
  http: ^0.13.5
  open_file: ^2.1.1
  table_calendar: ^3.0.9

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - .env
